site_name: Starfinder Lore
site_url: https://zendelll.github.io/starfinder-lore/
nav:
  - Таймлайн: timeline.md
  - Карта: map.md
  - Расы:
    - Краткое Описание: lore/races/index.md
    - Многочисленные:
      - Андроиды: lore/races/android.md
      - Вески: lore/races/vesk.md
      - Йсоки: lore/races/ysoki.md
      - Лашунта: lore/races/lashunta.md
      - Люди: lore/races/human.md
      - Пахтра: lore/races/pahtra.md
      - Скиттермандеры: lore/races/skittermander.md
      - Ширрены: lore/races/shirren.md
    - Малочисленные:
      - Астразоаны: lore/races/astrazoan.md
      - Барату: lore/races/barathu.md
      - Влака: lore/races/vlaka.md
      - Дракониды: lore/races/dragonkin.md
      - Кало: lore/races/kalo.md
      - Касатха: lore/races/kasatha.md
      - Контемплативы: lore/races/contemplative.md
      - Сарcесианы: lore/races/sarcesian.md
    - Подрасы (Наследия):
      - Борай: lore/races/heritages/borai.md
      - Присмени: lore/races/heritages/prismeni.md
  - Фракции:
    - Правительства:
      - Космическая Федерация: lore/governments/space-federation.md
      - Содружество Просвещения: lore/governments/lashunta.md
      - Теократия Единства: lore/governments/vesk.md
      - Звездный Совет: lore/governments/pahtra.md
      - Коллектив: lore/governments/shirren.md
    - Корпорации:
      - Amazon Interplanetary: lore/factions/corps/amazon-interplanetary.md
      - Apple Reality: lore/factions/corps/apple-reality.md
      - Google Synapse: lore/factions/corps/google-synapse.md
      - Yandex LLC: lore/factions/corps/yandex-llc.md
    - Независимые объединения:
      - Свободные Капитаны: lore/factions/free-captains.md
      - Адские Рыцари: lore/factions/hellknights.md
      - Рыцари Иомедеи: lore/factions/knights-of-iomedae.md
      - Общество Искателей Звезд: lore/factions/starfinder-society.md
      - Ксено-хранители: lore/factions/xenowardens.md
      - Клеймо Свободы: lore/factions/brand-of-freedom.md
  - Системы:
    - Космическая Федерация:
      - Люди:
        - Солнце: lore/systems/space-federation/human/sun.md
        - Альфа-Центавра: lore/systems/space-federation/human/alpha-centauri.md
        - Баззанак: lore/systems/space-federation/human/buzzanak.md
        - Венкворт: lore/systems/space-federation/human/wenkvort.md
        - Вермиллион: lore/systems/space-federation/human/vermillion.md
        - Вистрал: lore/systems/space-federation/human/vistral.md
        - Луо: lore/systems/space-federation/human/luo.md
        - Сириус: lore/systems/space-federation/human/sirius.md
        - HX-2247: lore/systems/space-federation/human/hx-2247.md
      - Йсоки:
        - Цевант: lore/systems/space-federation/ysoki/cevant.md
      - Андроиды:
        - Хестверн: lore/systems/space-federation/android/hestvern.md
  - Частые вопросы: index.md
theme:
  name: material
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Темная тема
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Светлая тема
extra_css:
  - css/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
